# Generated by Django 2.1.5 on 2019-02-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190210_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
