# Generated by Django 2.1.5 on 2019-02-11 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190211_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
