# Generated by Django 2.1.5 on 2019-02-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190212_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
    ]
